### ISSUE TITLE
Enable Direct links to Faction Pages

### ISSUE THREAD

**Issue by jamesrudolph** [Lazik10/TwilightImperiumUltimate#74]
to allow quick linking and easy google searches

something like:
https://ti4ultimate.com/game/factions?faction=titans&page=leaders
https://ti4ultimate.com/game/factions/titans

**Comment by Lazik10** [comment]
Thank you for your suggestion.

I added two optional page route parameters faction and info

Example: 
https://ti4ultimate.com/game/factions?faction=TheTitansOfUl&info=Setup
https://ti4ultimate.com/game/factions-discordant-stars?faction=TheDihMohnFlotilla&info=Setup

[supported info values](https://github.com/Lazik10/TwilightImperiumUltimate/blob/main/src/TwilightImperiumUltimate.Web/Enums/FactionInfoType.cs)
[supported faction values](https://github.com/Lazik10/TwilightImperiumUltimate/blob/main/src/TwilightImperiumUltimate.Contracts/Enums/FactionName.cs)

If parsing fails it should result in default (Arborec / Augurs and Ability)

This should help with direct links to specific faction and info, but to be honest I have no idea if this also solves the google search problem. I tried it and got no search results. And I have no idea how it works. I only know about SEO keyword, but that is all. I will try to learn more if I have time. 

(I will look at the Rules next over the weekend)
